name: rust

on: [push, pull_request]

jobs:
  build:
    env:
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]    
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose --all-features

# vim: sw=2 et
